### ISSUE TITLE
Wrong App import in App.story.js

### ISSUE THREAD

**Issue by alvaroabascar** [ritz078/react-component-boilerplate#4]
Within `App.story.js` App is wrongly imported.

![screenshot from 2017-06-19 16-47-41](https://user-images.githubusercontent.com/7307772/27290988-2b47b9ae-550f-11e7-99e2-a63f69a62b8e.png)

```{js}
import { App } from '../components';
```

Should be:

```{js}
import App from '../components';
```

**Comment by ritz078** [comment]
fixed
